apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-post-green
  labels:
    app: prod-backend1
    version: prod-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-backend1
      version: prod-green
  template:
    metadata:
      labels:
        app: prod-backend1
        version: prod-green
    spec:
      containers:
        - name: prod-backend1
          image: 423623850984.dkr.ecr.us-east-1.amazonaws.com/devops/post:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://database-2.cyxm60si8u5p.us-east-1.rds.amazonaws.com/jake_dbschema
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword123
