apiVersion: v1
kind: Service
metadata:
  name: prod-backend-post
spec:
  selector:
    app: prod-backend1
    version: prod-blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
