apiVersion: v1
kind: Service
metadata:
  name: uat-backend-post-green
spec:
  selector:
    app: uat-backend1
    version: green
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
