apiVersion: v1
kind: Service
metadata:
  name: prod-backend-signup-green
spec:
  selector:
    app: prod-backend2
    version: prod-green
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
