apiVersion: v1
kind: Service
metadata:
  name: uat-backend-post
spec:
  selector:
    app: uat-backend1
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
