apiVersion: v1
kind: Service
metadata:
  name: backend-post-green
spec:
  selector:
    app: prod-backend1
    version: prod-green
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
