apiVersion: v1
kind: Service
metadata:
  name: prod-frontend-green
spec:
  selector:
    app: prod-frontend-green
    version: prod-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP