apiVersion: v1
kind: Service
metadata:
  name: prod-frontend
spec:
  selector:
    app: prod-frontend
    version: prod-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

