apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-frontend
  labels:
    app: prod-frontend
    version: prod-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-frontend
      version: prod-blue
  template:
    metadata:
      labels:
        app: prod-frontend
        version: prod-blue
    spec:
      containers:
        - name: prod-frontend
          image: 423623850984.dkr.ecr.us-east-1.amazonaws.com/devops/front:latest
          ports:
            - containerPort: 80