apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: prod-frontend-green
    version: prod-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-frontend-green
      version: prod-green
  template:
    metadata:
      labels:
        app: prod-frontend-green
        version: prod-green
    spec:
      containers:
        - name: prod-frontend-green
          image: 423623850984.dkr.ecr.us-east-1.amazonaws.com/devops/frontgreen:latest
          ports:
            - containerPort: 80