apiVersion: v1
kind: Service
metadata:
  name: backend2-service-blue
spec:
  selector:
    app: backend2
    version: blue
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
