apiVersion: v1
kind: Service
metadata:
  name: backend1-service-blue
spec:
  selector:
    app: backend1
    version: blue
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
