apiVersion: v1
kind: Service
metadata:
  name: frontend-green
spec:
  selector:
    app: frontend-green
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
