apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat-frontend-blue
  labels:
    app: uat-frontend-blue
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uat-frontend
      version: blue
  template:
    metadata:
      labels:
        app: uat-frontend
        version: blue
    spec:
      containers:
        - name: uat-frontend
          image: 423623850984.dkr.ecr.us-east-1.amazonaws.com/devops/front:latest
          ports:
            - containerPort: 80