apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat-frontend-green
  labels:
    app: uat-frontend-green
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uat-frontend
      version: green
  template:
    metadata:
      labels:
        app: uat-frontend
        version: green
    spec:
      containers:
        - name: uat-frontend-green
          image: 423623850984.dkr.ecr.us-east-1.amazonaws.com/devops/frontgreen:latest
          ports:
            - containerPort: 80