apiVersion: v1
kind: Service
metadata:
  name: uat-frontend-blue
spec:
  selector:
    app: uat-frontend
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

