name: Deploy to UAT - Green

on:
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: your-eks-cluster-name
  AWS_REGION: us-east-1

jobs:
  deploy-green:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy Frontend Green (Deployment + Service)
        run: |
          kubectl apply -f k8s/frontend-deployment-green.yaml
          kubectl apply -f k8s/frontend-service-green.yaml

      - name: Wait for Green Pods to be Ready
        run: |
          kubectl rollout status deployment/frontend-deployment-green

      - name: Switch Ingress to Green
        run: |
          kubectl patch ingress app-ingress --type='json' -p='[
            {
              "op": "replace",
              "path": "/spec/rules/0/http/paths/0/backend/service/name",
              "value": "frontend-service-green"
            }
          ]'
